language: node_js
node_js:
- '6'
env:
  global:
    secure: V8wDymK+FArxaJ7gcDoemi19MYsHru+MY+uw0wbpfb7Xu925p0RYl1iLBsd5H1KSDKchwcb43oZGKqcux/dFWdMBTNuEtZ2LS+JF+OUh1TgusEHHiQsKh+4LGF9pqr25XWTosAeBsnbXANWT4IQjju6d7O3V5wpM6xLTJkhrglJZ5M2De3lejWNoybl2OeTwWdwdXLV0YC9L4NRMH8dLRwNiGZt5cfEYsOXcJcsoBYKdSzmtbLu/hL0fkB+7y8u5Kqlq7F/ulqPIfvxycOPLlVxWVZINC9pclMPfaPfZgfuaLtQP2T1JG3pow0dSAnIUWDiLCPx4J3OBa8nueZhe3oEnuSDSmLvJrWHk2ka7C1gnm+uwQpEkepIJy6wDn9LG9zzF5Ki5BCFAye0wAec/LxOvkS7PTLx+bgn0FQTbnhFnX2GyTsEUVFwtkk3a0VA2DowhVq2K44GynF6/sj+qlKfywhJ8Vm94RZzF6Z5mKuWiWnZv2+ATSO2k36qK77l+9wAGqoKL6kx6AOO1ozmGQY8NAch8z7qcZ14MrfeZLbULY9v1PoScQYpOlfGufvORqYhKHggOviUO2nY/R+8ra1KqUg6kUd9TAMXcc+g5q6oW8C2kHupsSmCqqYE5rXqK2udmk0Cm6k20LirYZXABKJdd7AChV7ORIeDhlL992fU=

